appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: owvpxiGbtap8eCfkz6Z8pehQpbQ9DEiz3ik//uVl+2gqk+ToQA8jLWOGkCGs4zT8ooYl89Vpw7fJuBWYrjSIFU8GqXGyTxFCKOeotmstXBWKautLVo8RGajOTOpmrxaUqLowNzxfaDzpqatd4AvDhIjh4CP7xtb0gi0TKrVV/USS4Y9BXZY1S3CZsqZM+tcO2j4aR+Wd62OoxKYGayK6xQVZKF2dao7LKVu8eq9ReY+t4rHSuy+CZKaANFYX2PV/U4mWeGutVfvMcoNYEeLo+kg220zEfW1be6eomQFveLmCDxZaE8t70X1shdF+IS0oQluSese+McQNcL/C2cbV8+eJBMVpvK3j7GYT378f+lqSxI4klT6VN3SZ/M18neUAiGBckXo5U34KyuCglCXY6F9yuhTUodkEllfZi4OnbpYld59b737WlzJqHh9xGMABYXjes5JljqlsFxH+55eBe6NY3g7hgYWWqJDEmhJEAtsk2o//TRkcd5x5vmF0XlL3vrETSNf9P5u4RA3bHLy8v1j5Oc+zH5UnNVA5154maEHJ7VuGtfbgOrZJRa6pOIl8vFddsauI/abUH50prjfToEfEMq+PAWYubkpwPCyBPsicMJLbpFkJZ5vSVVYHvPlpqdWtTvIuo+CskOnyjoIuNFejaLPzcyhvBNb80tkDmsU=}
